"""Module dr_bundle — 1-click disaster recovery bundle (R&D #16.8).

Produces a single tarball you can drop on a fresh box to reproduce the
dashboard's state in ~5 minutes :

  greenwatts-dr-<host>-<YYYYMMDD-HHMMSS>.tar.zst
  ├── manifest.json           (dashboard version + SHA-256 per file)
  ├── snapshot.db             (SQLite history, consistent via VACUUM INTO)
  ├── config/
  │    ├── config.env         (~/.config/gpu-dashboard/*.env)
  │    ├── tokens.json        (R&D #9.3, if exists)
  │    ├── boot_profile.json  (R&D #15.8, if exists)
  │    ├── rules.json         (R&D #12.4)
  │    ├── ...
  └── restore.sh              (idempotent, prompts before overwriting)

stdlib only : tarfile + subprocess(zstd) + hashlib.
"""
from __future__ import annotations

import hashlib
import json
import os
import socket
import subprocess
import tempfile
import time
from typing import Optional


NAME = "dr_bundle"

# Files to capture from ~/.config/gpu-dashboard/
_CONFIG_FILES = (
    "config.env",
    "tokens.json",                 # R&D #9.3 auth tokens (MIND: contains hashes only)
    ".server_secret",              # R&D #9.3 share-link signer
    "boot_profile.json",           # R&D #15.8
    "rules.json",                  # R&D #12.4
    "vram_quota.json",             # R&D #13.3
    "heartbeats.json",             # R&D #6.2
    "notif_channels.json",         # R&D #6.1
    "fan_curve.json",              # R&D #3 fan curve override
    "tariffs.csv",                 # R&D #15.2
    "grid_intensity.csv",          # R&D #13.4
    "users.allow",                 # R&D #14.2 lab accounting aliases
    "drift_snapshot.json",         # R&D #5.2 drift baseline
    "hot_swap_state.json",         # R&D #14.5
)


def _config_root() -> str:
    return os.path.expanduser("~/.config/gpu-dashboard")


def _bundles_dir() -> str:
    return os.path.expanduser("~/.config/gpu-dashboard/dr_bundles")


def _sha256_file(path: str) -> Optional[str]:
    h = hashlib.sha256()
    try:
        with open(path, "rb") as f:
            while True:
                buf = f.read(1024 * 1024)
                if not buf:
                    break
                h.update(buf)
    except OSError:
        return None
    return h.hexdigest()


def _vacuum_into(src_db_path: str, dst_path: str) -> bool:
    """Run SQLite's VACUUM INTO to produce a consistent snapshot file
    without stopping the live dashboard. Returns True on success."""
    if not os.path.exists(src_db_path):
        return False
    import sqlite3
    try:
        conn = sqlite3.connect(src_db_path)
        cur = conn.cursor()
        cur.execute(f"VACUUM INTO ?", (dst_path,))
        conn.close()
        return os.path.exists(dst_path) and os.path.getsize(dst_path) > 0
    except sqlite3.Error:
        return False


def _restore_script(bundle_basename: str, host: str) -> str:
    return f"""#!/usr/bin/env bash
# Idempotent restore script for gpu-dashboard DR bundle.
# Generated by dr_bundle.py on host: {host}
# Bundle: {bundle_basename}
set -euo pipefail

CFG_DIR="$HOME/.config/gpu-dashboard"
mkdir -p "$CFG_DIR"

echo "==> Restoring config files into $CFG_DIR (interactive prompt before overwrite)"
for f in config/*; do
    [ -e "$f" ] || continue
    name=$(basename "$f")
    dst="$CFG_DIR/$name"
    if [ -e "$dst" ]; then
        echo
        echo "  $dst already exists."
        printf "  Overwrite? [y/N] "
        read -r ANS
        if [ "$ANS" != "y" ] && [ "$ANS" != "Y" ]; then
            echo "  -> skipped $name"
            continue
        fi
    fi
    cp -v "$f" "$dst"
done

if [ -e snapshot.db ]; then
    DATA_DIR="$HOME/.local/share/gpu-dashboard"
    mkdir -p "$DATA_DIR"
    DST_DB="$DATA_DIR/history.db"
    if [ -e "$DST_DB" ]; then
        echo
        echo "  $DST_DB already exists."
        printf "  Overwrite? [y/N] "
        read -r ANS
        [ "$ANS" = "y" ] || [ "$ANS" = "Y" ] || {{ echo "  -> kept existing DB"; exit 0; }}
    fi
    cp -v snapshot.db "$DST_DB"
fi

echo
echo "==> Restore complete. Restart the dashboard :"
echo "    systemctl --user restart gpu-dashboard.service"
"""


def build_manifest(files: list, version: str = "?", host: str = "?",
                    bundle_ts: int = 0) -> dict:
    """SHA-256 each file + return a manifest dict."""
    entries: list = []
    for f in files:
        if not os.path.exists(f):
            continue
        st = os.stat(f)
        entries.append({
            "path": os.path.basename(f),
            "size_bytes": st.st_size,
            "sha256": _sha256_file(f),
            "mtime": int(st.st_mtime),
        })
    return {
        "dashboard_version": version,
        "host": host,
        "bundle_ts": bundle_ts,
        "file_count": len(entries),
        "files": entries,
    }


def build_bundle(history_db_path: Optional[str] = None,
                 version: str = "?", out_dir: Optional[str] = None) -> dict:
    """Assemble the DR bundle. Returns the path + manifest summary.

    Args :
      history_db_path : path to the SQLite history (default = read from
                        ~/.local/share/gpu-dashboard/history.db)
      version : dashboard version string (for the manifest)
      out_dir : where to write the bundle (default = ~/.config/.../dr_bundles)
    """
    cfg_root = _config_root()
    out_dir = out_dir or _bundles_dir()
    os.makedirs(out_dir, exist_ok=True)
    host = socket.gethostname()[:32]
    ts = int(time.time())
    ts_iso = time.strftime("%Y%m%d-%H%M%S", time.localtime(ts))
    name = f"greenwatts-dr-{host}-{ts_iso}"

    # Stage everything in a tmp dir, then tar it
    with tempfile.TemporaryDirectory() as staging:
        staged_root = os.path.join(staging, name)
        os.makedirs(staged_root)
        cfg_dst = os.path.join(staged_root, "config")
        os.makedirs(cfg_dst)

        # 1. Copy config files
        copied: list = []
        for fname in _CONFIG_FILES:
            src = os.path.join(cfg_root, fname)
            if not os.path.exists(src):
                continue
            dst = os.path.join(cfg_dst, fname)
            try:
                with open(src, "rb") as sf, open(dst, "wb") as df:
                    df.write(sf.read())
                copied.append(dst)
            except OSError:
                continue

        # 2. SQLite snapshot via VACUUM INTO
        db_src = history_db_path or os.path.expanduser(
            "~/.local/share/gpu-dashboard/history.db"
        )
        db_dst = os.path.join(staged_root, "snapshot.db")
        db_ok = _vacuum_into(db_src, db_dst)
        if db_ok:
            copied.append(db_dst)

        # 3. Manifest with SHA-256
        manifest = build_manifest(copied, version=version, host=host, bundle_ts=ts)
        with open(os.path.join(staged_root, "manifest.json"), "w") as f:
            json.dump(manifest, f, indent=2)

        # 4. restore.sh
        script_path = os.path.join(staged_root, "restore.sh")
        with open(script_path, "w") as f:
            f.write(_restore_script(name, host))
        os.chmod(script_path, 0o755)

        # 5. tar + zstd compress
        tar_path = os.path.join(out_dir, f"{name}.tar")
        zst_path = f"{tar_path}.zst"
        try:
            subprocess.run(["tar", "-cf", tar_path, "-C", staging, name],
                            check=True, capture_output=True, timeout=120)
        except (FileNotFoundError, subprocess.SubprocessError) as e:
            return {"ok": False, "error": f"tar failed: {e}"}

        # zstd (fall back to gzip if not available)
        try:
            subprocess.run(["zstd", "-19", "-q", "-f", "--rm", tar_path,
                            "-o", zst_path],
                            check=True, capture_output=True, timeout=60)
            final_path = zst_path
        except (FileNotFoundError, subprocess.SubprocessError):
            # Fallback : keep .tar
            final_path = tar_path
            try:
                subprocess.run(["gzip", "-9", "-f", tar_path],
                                check=True, capture_output=True, timeout=60)
                final_path = tar_path + ".gz"
            except (FileNotFoundError, subprocess.SubprocessError):
                pass

    if not os.path.exists(final_path):
        return {"ok": False, "error": "bundle artifact not produced"}

    return {
        "ok": True,
        "path": final_path,
        "name": os.path.basename(final_path),
        "size_bytes": os.path.getsize(final_path),
        "file_count": manifest["file_count"],
        "host": host,
        "bundle_ts": ts,
        "snapshot_db_included": db_ok,
    }


def list_bundles() -> list:
    """Recent bundles available locally."""
    d = _bundles_dir()
    if not os.path.isdir(d):
        return []
    out: list = []
    for name in sorted(os.listdir(d), reverse=True):
        path = os.path.join(d, name)
        try:
            st = os.stat(path)
        except OSError:
            continue
        out.append({
            "name": name, "path": path,
            "size_bytes": st.st_size,
            "ts": int(st.st_mtime),
        })
    return out


def delete_bundle(name: str) -> bool:
    """Delete a bundle by filename (basename only, no path traversal)."""
    if "/" in name or ".." in name:
        return False
    path = os.path.join(_bundles_dir(), name)
    if not os.path.isfile(path):
        return False
    try:
        os.remove(path)
        return True
    except OSError:
        return False
