"""Module net_sysctl_audit — LAN socket-buffer sysctl audit (R&D #35.2).

LLM inference daemons increasingly serve their HTTP/SSE responses
over LAN. The Linux defaults for socket-buffer sysctls were chosen
in an era of ~100-Mbps internet and 4 KiB pages; they're modest
for streaming a 4096-token SSE response on a Gigabit LAN:

  net.core.rmem_max               default 208 KiB — caps each
                                  socket's receive buffer
  net.core.wmem_max               default 208 KiB — same for send
  net.core.somaxconn              default 128 (Linux < 5.4) /
                                  4096 — listen() backlog cap
  net.core.netdev_max_backlog     default 1000 — per-CPU softirq
                                  packet queue

For LAN-served ollama / llama-server / vllm we want all four
elevated. The recipe drops a single /etc/sysctl.d/99-llm-lan.conf
Drop-In + `sysctl --system` reload.

Verdicts (per knob):
  ok        within or above LLM-friendly baseline
  warn      at default — flag + emit recommended value
  unknown   unreadable

Aggregate verdict = worst across the rows.

stdlib only.
"""
from __future__ import annotations

import os
from typing import Optional, Tuple


NAME = "net_sysctl_audit"


_SYSCTL_ROOT = "/proc/sys/net"


# Each entry: minimum acceptable value + recommended + reason.
_KNOBS: dict = {
    "core/rmem_max": {
        "min_ok": 4 * 1024 * 1024,           # ≥ 4 MiB
        "recommended": 16 * 1024 * 1024,     # 16 MiB
        "reason": ("rmem_max=208 KiB is the Linux default. Each LAN "
                    "socket receiving a streamed SSE response is capped "
                    "at this size, which serializes the client read loop."),
    },
    "core/wmem_max": {
        "min_ok": 4 * 1024 * 1024,
        "recommended": 16 * 1024 * 1024,
        "reason": ("wmem_max=208 KiB caps each socket's send buffer. For "
                    "the server side of a streamed SSE response that "
                    "means more TCP-level ACKs and lower effective "
                    "throughput on a Gigabit LAN."),
    },
    "core/somaxconn": {
        "min_ok": 1024,
        "recommended": 4096,
        "reason": ("somaxconn=128 caps the listen() backlog. On burst "
                    "client reconnects (browser refresh storms, "
                    "auto-reconnect SSE) the kernel silently drops "
                    "connection attempts."),
    },
    "core/netdev_max_backlog": {
        "min_ok": 2000,
        "recommended": 5000,
        "reason": ("netdev_max_backlog=1000 is the per-CPU softirq packet "
                    "queue. Under a burst of small SSE chunks this fills "
                    "and the kernel drops packets — same root cause as "
                    "the rx_dropped counter from #33.1 nic_health."),
    },
}


def read_sysctl(root: str, name: str) -> Optional[int]:
    p = os.path.join(root, name)
    try:
        with open(p) as f:
            s = f.read().strip()
    except OSError:
        return None
    try:
        return int(s)
    except ValueError:
        return None


def read_tcp_triple(root: str, name: str) -> Optional[Tuple[int, int, int]]:
    """tcp_rmem / tcp_wmem expose three integers (min default max)."""
    p = os.path.join(root, name)
    try:
        with open(p) as f:
            parts = f.read().split()
    except OSError:
        return None
    if len(parts) != 3:
        return None
    try:
        return (int(parts[0]), int(parts[1]), int(parts[2]))
    except ValueError:
        return None


def classify_one(name: str, value: Optional[int]) -> dict:
    spec = _KNOBS.get(name)
    if not spec:
        return {"name": name, "value": value, "severity": "unknown",
                "reason": "Unknown net.* sysctl.", "recommended": None}
    if value is None:
        return {"name": name, "value": None, "severity": "unknown",
                "reason": "Sysctl unreadable on this kernel.",
                "recommended": spec.get("recommended")}
    rec = spec["recommended"]
    if value >= spec["min_ok"]:
        return {"name": name, "value": value, "severity": "ok",
                "reason": "Above LLM-LAN baseline.", "recommended": rec}
    return {"name": name, "value": value, "severity": "warn",
            "reason": spec["reason"], "recommended": rec}


def aggregate(rows: list) -> str:
    if not rows:
        return "unknown"
    sevs = {r["severity"] for r in rows}
    if "warn" in sevs:
        return "warn"
    if "ok" in sevs:
        return "ok"
    return "unknown"


def make_recipe(flagged: list) -> str:
    if not flagged:
        return ""
    lines = [
        "# /etc/sysctl.d/99-llm-lan.conf — LAN socket-buffer tuning",
        "# Generated by gpu-dashboard, R&D #35.2 net_sysctl_audit",
    ]
    for f in flagged:
        # core/rmem_max → net.core.rmem_max
        key = "net." + f["name"].replace("/", ".")
        lines.append(f"{key}={f['recommended']}")
    lines.append("")
    lines.append("# Apply now without reboot:")
    lines.append("sudo sysctl --system")
    return "\n".join(lines)


def status(cfg=None) -> dict:
    if not os.path.isdir(_SYSCTL_ROOT):
        return {"ok": False, "error": "net_sysctl_unavailable",
                "reason": f"{_SYSCTL_ROOT} not present."}
    rows: list = []
    for name in _KNOBS:
        v = read_sysctl(_SYSCTL_ROOT, name)
        if v is None:
            continue
        rows.append(classify_one(name, v))
    # Informational extras
    tcp_rmem = read_tcp_triple(_SYSCTL_ROOT, "ipv4/tcp_rmem")
    tcp_wmem = read_tcp_triple(_SYSCTL_ROOT, "ipv4/tcp_wmem")
    flagged = [r for r in rows if r["severity"] == "warn"
                and r.get("recommended") is not None]
    return {
        "ok": True,
        "rows": rows,
        "row_count": len(rows),
        "flagged_count": len(flagged),
        "worst_severity": aggregate(rows),
        "tcp_rmem": tcp_rmem,
        "tcp_wmem": tcp_wmem,
        "recipe": make_recipe(flagged),
    }
