"""HTTP handlers for alerts + multi-channel notifications + deadman heartbeats.

Extracted from the legacy monolith in cycle 8 of the api/ split.
Covers R&D #3 alerts threshold config + R&D #6.1 Notif Hub (Discord,
Slack, ntfy, Pushover, Gotify, generic webhook, SMTP) + R&D #6.2
deadman heartbeats.
"""
from __future__ import annotations

import json
import os
import time
from typing import Optional, Tuple

from . import _core as _m


Response = Tuple[int, dict]


# Forwarding stubs : tests patching api._core.X are honored here.
def _gpus_available():
    return _m._gpus_available()


def _gpu_card_snapshot(gpu_index: int = 0):
    return _m._gpu_card_snapshot(gpu_index)


# ─────────────── GET / POST /api/alerts-config ────────────────────────────


def handle_alerts_config_get(ctx: dict) -> Response:
    cfg = ctx["config"]
    return 200, {
        "enabled": cfg.get_bool("TG_ENABLED", default=False),
        "token": cfg.get("TG_TOKEN", ""),
        "chat_id": cfg.get("TG_CHAT", ""),
        "on_drop": cfg.get_bool("ALERT_DROP", default=True),
        "on_recover": cfg.get_bool("ALERT_RECOVER", default=True),
    }

def handle_alerts_config_post(ctx: dict, payload: dict) -> Response:
    """Save alerts config to secrets.env (chmod 600)."""
    cfg = ctx["config"]
    secrets_path = os.path.expanduser(
        cfg.get("ALERTS_SECRETS_PATH", "~/.config/gpu-dashboard/secrets.env")
    )

    token = str(payload.get("token", "")).strip()
    chat_id = str(payload.get("chat_id", "")).strip()
    enabled = bool(payload.get("enabled", False))

    if enabled and (not token or not chat_id):
        return 400, {"ok": False, "error": "token and chat_id required when enabled"}

    # Write secrets.env
    from ..config import write_env_file
    os.makedirs(os.path.dirname(secrets_path), exist_ok=True)
    new_values = {
        "TG_ENABLED": "1" if enabled else "0",
        "TG_TOKEN": token,
        "TG_CHAT": chat_id,
        "ALERT_DROP": "1" if payload.get("on_drop", True) else "0",
        "ALERT_RECOVER": "1" if payload.get("on_recover", True) else "0",
    }
    write_env_file(secrets_path, new_values,
                    header="# Auto-generated by gpu-dashboard. chmod 600.")
    os.chmod(secrets_path, 0o600)
    # Critical: also update the in-memory Config so subsequent
    # endpoints (Test, alert dispatch, …) see the new values without
    # requiring a dashboard restart. Without this, Save→Test in the
    # same session always fails with "token or chat_id missing"
    # because cfg.get(TG_TOKEN) returns the stale empty value.
    for k, v in new_values.items():
        cfg.set(k, v)
    return 200, {"ok": True}

def handle_alerts_detect_chat_id(ctx: dict, payload: dict) -> Response:
    """F8 — Auto-detect the user's chat_id by polling Telegram's
    getUpdates endpoint.

    Workflow from the user's POV:
      1. Open Telegram, send any message to your bot
      2. Click "🔍 Detect chat_id" in the dashboard
      3. The field auto-fills with the chat_id of whoever just messaged

    Removes the curl/JSON-parse friction that bit the first user
    during the Telegram setup flow.
    """
    import json as _json
    import urllib.request
    import urllib.error
    import socket

    cfg = ctx["config"]
    # Accept token from the request body (so the user can detect
    # before saving) OR fall back to the stored value.
    token = (payload.get("token") if payload else None) or cfg.get("TG_TOKEN", "")
    token = str(token or "").strip()
    if not token:
        return 400, {"ok": False, "error": "token_missing",
                      "message": "Provide the bot token first"}
    # Defensive format check before hitting Telegram.
    if ":" not in token or len(token) < 30:
        return 400, {"ok": False, "error": "token_format",
                      "message": "Token format looks wrong (expected <bot_id>:<secret>)"}

    url = f"https://api.telegram.org/bot{token}/getUpdates"
    try:
        with urllib.request.urlopen(url, timeout=4.0) as r:
            data = _json.loads(r.read().decode("utf-8"))
    except urllib.error.HTTPError as e:
        return 502, {"ok": False, "error": "telegram_http",
                      "message": f"Telegram returned {e.code}: "
                                 f"check token validity"}
    except (urllib.error.URLError, socket.timeout) as e:
        return 502, {"ok": False, "error": "network",
                      "message": f"Could not reach Telegram: {e}"}
    except ValueError:
        return 502, {"ok": False, "error": "parse",
                      "message": "Telegram returned non-JSON"}

    if not data.get("ok"):
        return 502, {"ok": False, "error": "telegram_rejected",
                      "message": data.get("description", "unknown")}

    # Walk updates newest-first to find the most recent chat any
    # message came from. Channel posts also count.
    candidates = []
    for u in (data.get("result") or [])[::-1]:
        msg = u.get("message") or u.get("channel_post") or {}
        chat = msg.get("chat") or {}
        cid = chat.get("id")
        if cid is None:
            continue
        candidates.append({
            "chat_id": str(cid),
            "type": chat.get("type"),
            "name": (chat.get("title")
                      or chat.get("username")
                      or chat.get("first_name")
                      or "?"),
            "last_text": (msg.get("text") or "")[:60],
        })
        # Deduplicate by chat_id (multiple updates from same chat)
        seen = {c["chat_id"] for c in candidates}
        if len(seen) >= 5:
            break
    if not candidates:
        return 200, {"ok": True, "chat_id": None, "candidates": [],
                      "hint": ("No messages found. Send any message "
                               "to your bot in Telegram first, then "
                               "click Detect again.")}
    # Dedupe (most recent first by virtue of reversed iteration)
    seen: dict = {}
    for c in candidates:
        seen.setdefault(c["chat_id"], c)
    unique = list(seen.values())
    return 200, {
        "ok": True,
        "chat_id": unique[0]["chat_id"],  # best guess = most recent
        "candidates": unique,
    }


def handle_alerts_latest(ctx: dict) -> Response:
    """Return the most-recent alert event.

    Called by the service worker on push receipt to fetch the alert text
    (avoids needing RFC 8291 encrypted payloads — push is just a 'wake up
    and check' signal, SW fetches details here).
    """
    storage = ctx.get("storage")
    if storage is None:
        return 503, {"ok": False, "error": "storage not available"}
    events = storage.get_events(from_ts=0, kind="alert")
    if not events:
        return 200, {"ok": True, "alert": None}
    # Most recent first
    latest = max(events, key=lambda e: e["ts"])
    return 200, {"ok": True, "alert": latest}

# ─── R&D #7.10 — Prometheus AlertManager rules export ────────────────────────
def _alert_consecutive_to_for(min_n: int, interval_s: int) -> str:
    """Translate 'N consecutive samples at <interval>s' into Prom 'for: Xs'."""
    return f"{int(min_n) * int(interval_s)}s"

# ─── R&D #6.1 — Unified notification hub (Apprise-style fanout) ──────────────
def handle_notif_channels_list(ctx: dict) -> Response:
    """Return all configured channels (with secrets masked)."""
    from ..modules import notif_hub as _nh
    channels = _nh.load_channels()
    out: list = []
    for ch in channels:
        masked = dict(ch)
        # Mask sensitive fields
        for k in ("token", "password", "user", "url"):
            if k in masked and isinstance(masked[k], str) and len(masked[k]) > 8:
                masked[k] = masked[k][:6] + "…" + masked[k][-3:]
        out.append(masked)
    return 200, {"ok": True, "channels": out,
                 "types_supported": list(_nh._ADAPTERS.keys())}

def handle_notif_channel_save(ctx: dict, payload: dict) -> Response:
    """Create or update a channel by id. Payload :
      {id, type, name, enabled, min_level, gpu_filter, quiet_hours, ...adapter-specific...}
    Or {delete: id}."""
    from ..modules import notif_hub as _nh
    if not isinstance(payload, dict):
        return 400, {"ok": False, "error": "payload must be a dict"}
    channels = _nh.load_channels()
    if "delete" in payload:
        target = str(payload["delete"])
        channels = [c for c in channels if c.get("id") != target]
        _nh.save_channels(channels)
        return 200, {"ok": True, "deleted": target}

    cid = str(payload.get("id", "")).strip()
    ctype = str(payload.get("type", "")).strip()
    if not cid:
        return 400, {"ok": False, "error": "id required"}
    if ctype not in _nh._ADAPTERS:
        return 400, {"ok": False, "error": f"unknown type. Available : {list(_nh._ADAPTERS.keys())}"}

    # Replace existing or append
    new_channel = {k: v for k, v in payload.items() if k != "_test"}
    channels = [c for c in channels if c.get("id") != cid] + [new_channel]
    _nh.save_channels(channels)
    return 200, {"ok": True, "id": cid}

def handle_notif_channel_test(ctx: dict, payload: dict) -> Response:
    """Fire a test notification to the channel specified in payload (no save).
    Useful before saving — user can validate the credentials inline."""
    from ..modules import notif_hub as _nh
    if not isinstance(payload, dict) or "type" not in payload:
        return 400, {"ok": False, "error": "payload requires 'type'"}
    ok, msg = _nh.send_test(payload)
    code = 200 if ok else 502
    return code, {"ok": ok, "msg": msg}

def _load_heartbeats() -> dict:
    """Persist shape : {tokens: {<token>: {name, interval_s, grace_s, last_seen_ts}}}.
    Returns {tokens: {}} if missing."""
    path = _heartbeats_path()
    if not os.path.exists(path):
        return {"tokens": {}}
    try:
        with open(path) as f:
            data = json.load(f)
        if not isinstance(data, dict) or "tokens" not in data:
            return {"tokens": {}}
        return data
    except (OSError, json.JSONDecodeError):
        return {"tokens": {}}

def _save_heartbeats(data: dict) -> None:
    path = _heartbeats_path()
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "w") as f:
        json.dump(data, f, indent=2)

def handle_heartbeat_list(ctx: dict) -> Response:
    """List all heartbeat tokens + their current status (ok/late/never)."""
    data = _load_heartbeats()
    now = int(time.time())
    items: list = []
    for token, hb in (data.get("tokens") or {}).items():
        last_seen = hb.get("last_seen_ts")
        interval = int(hb.get("interval_s", 3600))
        grace = int(hb.get("grace_s", 300))
        if last_seen is None:
            status = "never"
            age_s = None
        else:
            age_s = now - int(last_seen)
            status = "ok" if age_s <= interval + grace else "late"
        items.append({
            "token": token,
            "name": hb.get("name", token),
            "interval_s": interval,
            "grace_s": grace,
            "last_seen_ts": last_seen,
            "age_s": age_s,
            "status": status,
        })
    items.sort(key=lambda x: x.get("age_s") if x.get("age_s") is not None else -1, reverse=True)
    return 200, {"ok": True, "heartbeats": items}

def handle_heartbeat_ping(ctx: dict, token: str) -> Response:
    """Inbound : record a ping from a training script.

    Usage : `curl -fsS http://host/api/heartbeat/<token>`
    Token must already exist (created via POST /api/heartbeat/config).
    """
    data = _load_heartbeats()
    if token not in (data.get("tokens") or {}):
        return 404, {"ok": False, "error": "unknown heartbeat token"}
    data["tokens"][token]["last_seen_ts"] = int(time.time())
    _save_heartbeats(data)
    return 200, {"ok": True, "token": token, "ts": data["tokens"][token]["last_seen_ts"]}

def handle_heartbeat_config(ctx: dict, payload: dict) -> Response:
    """Create or update a heartbeat token.

    Payload :
      {token: str, name: str, interval_s: int, grace_s: int}
      OR {delete: token}
    """
    if not isinstance(payload, dict):
        return 400, {"ok": False, "error": "payload must be a dict"}
    data = _load_heartbeats()
    if "delete" in payload:
        token = str(payload["delete"])
        if token in data.get("tokens", {}):
            del data["tokens"][token]
            _save_heartbeats(data)
        return 200, {"ok": True, "deleted": token}
    token = str(payload.get("token", "")).strip()
    if not token or not all(c.isalnum() or c in "-_" for c in token):
        return 400, {"ok": False, "error": "token must be alphanumeric + - _"}
    name = str(payload.get("name", token)).strip()
    try:
        interval_s = int(payload.get("interval_s", 3600))
        grace_s = int(payload.get("grace_s", 300))
    except (TypeError, ValueError):
        return 400, {"ok": False, "error": "interval_s and grace_s must be integers"}
    if interval_s < 30 or interval_s > 7 * 86400:
        return 400, {"ok": False, "error": "interval_s out of range [30, 604800]"}
    if grace_s < 0 or grace_s > interval_s:
        return 400, {"ok": False, "error": "grace_s must be in [0, interval_s]"}
    existing = data.get("tokens", {}).get(token, {})
    data.setdefault("tokens", {})[token] = {
        "name": name,
        "interval_s": interval_s,
        "grace_s": grace_s,
        "last_seen_ts": existing.get("last_seen_ts"),  # preserve on edit
    }
    _save_heartbeats(data)
    return 200, {"ok": True, "token": token}


# Helper from cycle 8 — heartbeats persistence path
def _heartbeats_path() -> str:
    return os.path.expanduser("~/.config/gpu-dashboard/heartbeats.json")
