"""Installation interactive — détecte l'environnement, recommande des modules,
génère les fichiers de config et les unit files systemd.

Conçu pour respecter l'utilisateur :
- Aucune commande sudo n'est lancée automatiquement
- Le script affiche les commandes à coller, l'utilisateur garde la main
- Toutes les recommandations sont basées sur la détection live (jamais d'estimations)

Architecture :
- main() — orchestration interactive (input() prompts)
- recommend_modules(env) — pure : prend un dict env, retourne la liste des modules
  avec leur disponibilité + recommandation
- generate_*() — pures : produisent les contenus de config.env, sudoers, systemd unit
"""
from __future__ import annotations

import argparse
import os
import subprocess
import sys
from typing import List, Optional, Tuple

from .detect import (
    detect_os,
    detect_nvidia,
    detect_coolbits,
    detect_virt,
    detect_external_gpu_link,
)
from .profile import get_profile_for_gpu


_DEFAULT_WRAPPER = "/usr/local/bin/set-power-limit"

# Bit du Coolbits requis pour les sliders OC
_COOLBITS_OC = 8


# ──────────────────────────── recommend_modules ────────────────────────────


def recommend_modules(env: dict) -> list:
    """À partir d'un dict env (issu des detect.*), retourne la liste des modules
    avec leur état d'activabilité et de recommandation.

    Chaque entrée : {"name", "available", "recommend", "reason"}.
    """
    coolbits = env.get("coolbits", {})
    cb_value = coolbits.get("value") or 0
    has_oc_bit = coolbits.get("enabled") and (cb_value & _COOLBITS_OC)

    external = env.get("external_gpu", {}).get("likely_external", False)
    vm = env.get("virt", {}).get("is_vm", False)
    has_egpu_signs = external or vm

    wrapper_exists = env.get("power_wrapper_exists", False)

    return [
        {
            "name": "power_limit",
            "available": wrapper_exists,
            "recommend": True,
            "reason": (
                "sudoers wrapper in place ✓"
                if wrapper_exists
                else f"wrapper missing at {_DEFAULT_WRAPPER} — sudo install needed (the installer will tell you how)"
            ),
        },
        {
            "name": "clock_offsets",
            "available": bool(has_oc_bit),
            "recommend": True,
            "reason": (
                f"Coolbits={cb_value} with OC bit ✓"
                if has_oc_bit
                else f"Coolbits missing or OC bit absent (current value: {cb_value or 'none'})"
            ),
        },
        {
            "name": "telegram_alerts",
            "available": True,
            "recommend": False,
            "reason": "works anywhere — requires a bot token + chat ID provided later",
        },
        {
            "name": "oculink_watchdog",
            "available": True,
            "recommend": has_egpu_signs,
            "reason": (
                "external GPU signs detected (x4 link or VM passthrough) ✓"
                if has_egpu_signs
                else "no eGPU/Thunderbolt signs — module probably not useful"
            ),
        },
    ]


# ──────────────────────────── generate_config_env ──────────────────────────


def generate_config_env(
    choices: dict,
    port: int = 9999,
    power_default: int = 250,
    bind: str = "0.0.0.0",
) -> str:
    """Génère le contenu de `~/.config/gpu-dashboard/config.env`."""
    def b(name: str) -> int:
        return 1 if choices.get(name) else 0
    return f"""# ~/.config/gpu-dashboard/config.env
# Auto-generated by install.sh. Editable manually afterwards.

# === Dashboard HTTP ===
DASHBOARD_PORT={port}
DASHBOARD_BIND={bind}
DASHBOARD_REFRESH_INTERVAL=5
DASHBOARD_SAMPLE_KEEP=720

# === Opt-in modules (0 = disabled, 1 = enabled) ===
MODULE_POWER_LIMIT={b("power_limit")}
MODULE_CLOCK_OFFSETS={b("clock_offsets")}
MODULE_TELEGRAM_ALERTS={b("telegram_alerts")}
MODULE_OCULINK_WATCHDOG={b("oculink_watchdog")}
MODULE_FAN_CURVE={b("fan_curve")}

# === Power limit ===
POWER_LIMIT_DEFAULT={power_default}
POWER_LIMIT_WRAPPER={_DEFAULT_WRAPPER}

# === Clock offsets ===
# DISPLAY is the X server attached to the NVIDIA (often :0)
CLOCK_OFFSETS_DISPLAY=:0
# CLOCK_OFFSETS_XAUTHORITY=  # optional, usually auto-detected

# === OcuLink watchdog ===
OCULINK_POLL_INTERVAL=60
"""


# ─────────────────────────────── generate_sudoers ──────────────────────────


def generate_sudoers(user: str, wrapper_path: str = _DEFAULT_WRAPPER) -> str:
    """Génère le contenu d'un fichier `/etc/sudoers.d/gpu-dashboard`.

    Strictement ciblé : autorise seulement l'exécution du wrapper, pas d'autres
    commandes. Aucun wildcard dans le path.
    """
    return f"""# /etc/sudoers.d/gpu-dashboard
# Auto-generated by gpu-dashboard install. To install:
#   sudo cp <this-file> /etc/sudoers.d/gpu-dashboard
#   sudo chmod 0440 /etc/sudoers.d/gpu-dashboard
#   sudo visudo -c -f /etc/sudoers.d/gpu-dashboard

{user} ALL=(root) NOPASSWD: {wrapper_path}
"""


# ─────────────────────────── generate_systemd_unit ─────────────────────────


def generate_power_limit_wrapper() -> str:
    """Generate the /usr/local/bin/set-power-limit wrapper script.

    A small bash wrapper that validates its argument (integer 100-350W) before
    calling `nvidia-smi -pl`. Designed to be the sole entry point allowed by the
    sudoers rule, so no other root command becomes accessible.
    """
    return """#!/usr/bin/env bash
# Wrapper for `nvidia-smi -pl`, called via passwordless sudoers.
# Validates its argument strictly and persists the value to
# /etc/default/gpu-powerlimit so the systemd service re-applies at boot.
set -e
W="$1"
if ! [[ "$W" =~ ^[0-9]+$ ]] || (( W < 100 )) || (( W > 350 )); then
  echo "ERROR: argument must be an integer between 100 and 350 (watts), got: '$W'" >&2
  exit 2
fi

# Persist for reboot
STATE=/etc/default/gpu-powerlimit
TMP=$(mktemp)
echo "WATTS=$W" > "$TMP"
mv "$TMP" "$STATE"
chmod 0644 "$STATE"

exec /usr/bin/nvidia-smi -pl "$W"
"""


def generate_coolbits_xorg_conf(
    bus_id: str = "PCI:1:0:0",
    headless: bool = False,
) -> str:
    """Generate an Xorg drop-in to enable Coolbits=12 on the NVIDIA.

    Args:
        bus_id: PCIe address in Xorg format (e.g. "PCI:1:0:0" for 01:00.0)
        headless: True if the NVIDIA has no attached monitor (VM passthrough,
                  eGPU, SSH-only). Adds AllowEmptyInitialConfiguration +
                  ConnectedMonitor so Xorg can start without a display.
    """
    head = """Section "ServerLayout"
    Identifier "Layout0"
    Screen 0 "Screen0"
EndSection

Section "Monitor"
    Identifier "Monitor0"
    HorizSync   28.0 - 33.0
    VertRefresh 43.0 - 72.0
EndSection
""" if headless else ""

    device = f"""Section "Device"
    Identifier "Nvidia GPU"
    Driver "nvidia"
    BusID "{bus_id}"
    Option "Coolbits" "12"
"""
    if headless:
        device += """    Option "AllowEmptyInitialConfiguration" "true"
    Option "ConnectedMonitor" "DFP-0"
    Option "UseDisplayDevice" "DFP-0"
"""
    device += "EndSection\n"

    screen = """
Section "Screen"
    Identifier "Screen0"
    Device "Nvidia GPU"
    Monitor "Monitor0"
    DefaultDepth 24
    SubSection "Display"
        Depth 24
        Modes "1920x1080" "1024x768"
    EndSubSection
EndSection
""" if headless else ""

    flags = """
Section "ServerFlags"
    Option "AutoAddGPU" "false"
    Option "AutoBindGPU" "false"
EndSection
""" if headless else ""

    return f"{flags}{head}{device}{screen}"


def generate_systemd_unit(
    description: str,
    exec_start: str,
    env_file: str,
    after: str = "default.target",
    restart: str = "on-failure",
) -> str:
    """Génère un unit systemd user (à poser dans ~/.config/systemd/user/)."""
    return f"""[Unit]
Description={description}
After={after}

[Service]
Type=simple
EnvironmentFile=-{env_file}
ExecStart={exec_start}
Restart={restart}
RestartSec=10

[Install]
WantedBy={after}
"""


# ─────────────────────────────── main interactif ───────────────────────────


def _yn(prompt: str, default: bool = False) -> bool:
    suffix = "[Y/n]" if default else "[y/N]"
    ans = input(f"{prompt} {suffix} ").strip().lower()
    if not ans:
        return default
    return ans in ("y", "yes", "o", "oui")


def _offer_sudo_install(
    label: str,
    file_ops: List[Tuple[str, str, Optional[int]]],
    post_commands: Optional[List[List[str]]] = None,
) -> bool:
    """Show planned sudo operations, ask for confirmation, then execute.

    Args:
        label: short name shown in messages (e.g. "sudoers rule").
        file_ops: list of (src_path, dest_path, mode_or_None). Each becomes
                  a `sudo cp` + optional `sudo chmod`.
        post_commands: extra commands to run as root after the file ops.

    Returns True on success, False on cancel or any failure.
    """
    print(f"\n  \033[1mProposed actions for {label}:\033[0m")
    for src, dest, mode in file_ops:
        print(f"    sudo cp {src} {dest}")
        if mode is not None:
            print(f"    sudo chmod {oct(mode)[2:]} {dest}")
    for cmd in (post_commands or []):
        print(f"    sudo {' '.join(cmd)}")

    if not _yn("\n  Run these now via sudo (will prompt for password)?", default=False):
        print(f"  Skipped — you can run them manually later.")
        return False

    try:
        for src, dest, mode in file_ops:
            subprocess.run(["sudo", "cp", src, dest], check=True)
            if mode is not None:
                subprocess.run(["sudo", "chmod", oct(mode)[2:], dest], check=True)
        for cmd in (post_commands or []):
            subprocess.run(["sudo"] + cmd, check=True)
    except subprocess.CalledProcessError as e:
        print(f"\033[31m✗\033[0m sudo command failed: {e}")
        return False
    except KeyboardInterrupt:
        print("\n\033[33m⚠\033[0m Cancelled by user.")
        return False

    print(f"  \033[32m✓\033[0m {label} installed")
    return True


def _gather_env() -> dict:
    """Sonde l'environnement live (lit fichiers + appelle nvidia-smi/etc.)."""
    nvidia = detect_nvidia()
    gpu_bus = nvidia["gpus"][0]["bus_id"] if nvidia.get("gpus") else "0000:01:00.0"
    return {
        "os": detect_os(),
        "nvidia": nvidia,
        "coolbits": detect_coolbits(),
        "virt": detect_virt(),
        "external_gpu": detect_external_gpu_link(gpu_bus),
        "power_wrapper_exists": os.path.isfile(_DEFAULT_WRAPPER),
    }


def _print_summary(env: dict, profile: Optional[dict]) -> None:
    print()
    print("\033[1m🔍 Environment detection\033[0m")
    print("─" * 60)
    os_info = env["os"]
    print(f"  OS          : {os_info.get('pretty_name') or '?'} ({os_info.get('package_manager') or 'unknown pkg manager'})")
    nv = env["nvidia"]
    if nv["available"]:
        print(f"  NV driver   : {nv['driver_version']}")
        for i, gpu in enumerate(nv["gpus"]):
            print(f"  GPU [{i}]     : {gpu['name']} ({gpu['vram_mib']} MiB) — bus {gpu['bus_id']}")
        if profile:
            print(f"  Profile     : {profile.get('model', '?')}")
    else:
        print("  NV driver   : \033[31mnot available\033[0m — install.sh cannot proceed")
    cb = env["coolbits"]
    print(f"  Coolbits    : {'configured (' + str(cb['value']) + ')' if cb['enabled'] else 'not configured'}")
    ext = env["external_gpu"]
    if ext.get("link_width"):
        print(f"  PCIe link   : x{ext['link_width']} {'(likely eGPU)' if ext['likely_external'] else ''}")
    virt = env["virt"]
    if virt["is_vm"]:
        print(f"  Virt        : {virt['type']} (likely VM passthrough)")


def main(argv: Optional[list] = None) -> int:
    parser = argparse.ArgumentParser(
        description="gpu-dashboard installer — detect + recommend + install"
    )
    parser.add_argument("--detect-only", action="store_true",
                        help="Show detection only, don't install anything")
    parser.add_argument("--profiles-dir", default="profiles",
                        help="Directory containing the JSON profiles")
    args = parser.parse_args(argv)

    env = _gather_env()
    gpu_name = env["nvidia"]["gpus"][0]["name"] if env["nvidia"]["gpus"] else ""
    profile = get_profile_for_gpu(args.profiles_dir, gpu_name) if gpu_name else None

    _print_summary(env, profile)

    if not env["nvidia"]["available"]:
        print("\n\033[31m✗ No NVIDIA driver detected. Aborting install.\033[0m")
        return 2

    recs = recommend_modules(env)
    print("\n\033[1m🧩 Available modules\033[0m")
    print("─" * 60)
    for r in recs:
        status = "\033[32m✓\033[0m" if r["available"] else "\033[33m⚠\033[0m"
        flag = " (recommended)" if r["recommend"] else ""
        print(f"  {status} {r['name']:18s} {r['reason']}{flag}")

    if args.detect_only:
        return 0

    print("\n\033[1m📋 Module selection\033[0m")
    print("─" * 60)
    choices = {}
    for r in recs:
        default = r["available"] and r["recommend"]
        if not r["available"]:
            print(f"  - {r['name']:18s} \033[33mdisabled (missing prerequisite)\033[0m")
            choices[r["name"]] = False
            continue
        choices[r["name"]] = _yn(f"  Enable {r['name']}?", default=default)

    print("\n\033[1m📝 Files to generate\033[0m")
    print("─" * 60)
    home = os.path.expanduser("~")
    config_path = os.path.join(home, ".config/gpu-dashboard/config.env")
    config_content = generate_config_env(choices)
    print(f"  → {config_path}  (~{len(config_content)} bytes)")
    print()
    print("Config preview:")
    print("\n".join("    " + line for line in config_content.splitlines()[:8]))
    print("    ...")

    if not _yn("\nWrite files?", default=True):
        print("Cancelled. No files written.")
        return 0

    os.makedirs(os.path.dirname(config_path), exist_ok=True)
    with open(config_path, "w") as f:
        f.write(config_content)
    print(f"\n\033[32m✓\033[0m {config_path}")

    # ── Power limit: wrapper script + sudoers rule ──────────────────────────
    if choices.get("power_limit") and not env["power_wrapper_exists"]:
        cache_dir = os.path.join(home, ".cache/gpu-dashboard")
        os.makedirs(cache_dir, exist_ok=True)
        wrapper_src = os.path.join(cache_dir, "set-power-limit")
        sudoers_src = os.path.join(cache_dir, "sudoers-gpu-dashboard")
        with open(wrapper_src, "w") as f:
            f.write(generate_power_limit_wrapper())
        os.chmod(wrapper_src, 0o755)
        with open(sudoers_src, "w") as f:
            f.write(generate_sudoers(user=os.environ.get("USER", "user")))
        print("\n\033[33m⚠\033[0m \033[1mpower_limit module requires a sudoers wrapper to be installed.\033[0m")
        _offer_sudo_install(
            label="power-limit wrapper + sudoers rule",
            file_ops=[
                (wrapper_src, "/usr/local/bin/set-power-limit", 0o755),
                (sudoers_src, "/etc/sudoers.d/gpu-dashboard", 0o440),
            ],
            post_commands=[["visudo", "-c", "-f", "/etc/sudoers.d/gpu-dashboard"]],
        )

    # ── Clock offsets: Xorg Coolbits drop-in ────────────────────────────────
    if choices.get("clock_offsets") and not env["coolbits"].get("enabled"):
        bus_id_xorg = "PCI:1:0:0"
        if env["nvidia"]["gpus"]:
            bus_id_raw = env["nvidia"]["gpus"][0]["bus_id"]
            try:
                parts = bus_id_raw.split(":")
                if len(parts) == 3:
                    bus_id_xorg = f"PCI:{int(parts[1], 16)}:{int(parts[2].split('.')[0], 16)}:0"
            except (ValueError, IndexError):
                pass
        is_headless = env["external_gpu"].get("likely_external") or env["virt"].get("is_vm")
        cache_dir = os.path.join(home, ".cache/gpu-dashboard")
        os.makedirs(cache_dir, exist_ok=True)
        xorg_src = os.path.join(cache_dir, "20-nvidia-coolbits.conf")
        with open(xorg_src, "w") as f:
            f.write(generate_coolbits_xorg_conf(bus_id=bus_id_xorg, headless=is_headless))
        print(f"\n\033[33m⚠\033[0m \033[1mclock_offsets module requires Coolbits in xorg.conf.\033[0m")
        print(f"   Generated config mode: {'headless (VM/eGPU detected)' if is_headless else 'simple'}")
        _offer_sudo_install(
            label="Coolbits Xorg config",
            file_ops=[
                (xorg_src, "/etc/X11/xorg.conf.d/20-nvidia-coolbits.conf", 0o644),
            ],
        )
        print("   \033[33mNote:\033[0m the Coolbits change takes effect on the next X restart")
        print("   (logout/login your desktop session, or reboot).")
        if is_headless:
            print("\n   \033[33mHeadless setup detected.\033[0m The Coolbits drop-in alone is NOT enough")
            print("   if no X server is attached to the NVIDIA. You'll also need:")
            print("     - sddm autologin into a no-op session")
            print("     - A session script that keeps Xorg :0 alive on the NVIDIA")
            print("   This is documented in docs/HEADLESS_SETUP.md (v0.2 will automate it).")

    print("\n\033[32m✓ Install complete\033[0m. Start the dashboard with:")
    print("    python3 -m gpu_dashboard.server")
    return 0


if __name__ == "__main__":
    sys.exit(main())
